### ISSUE TITLE
本地启动的时候报错

### ISSUE THREAD

**Issue by wenyang0710** [kuangshp/admin-web-vue3-typescript#19]
runtime-core.esm-bundler.js?5c40:218 Uncaught TypeError: Object(...) is not a function，如下图

![vue3-admin-error](https://user-images.githubusercontent.com/16591026/133051111-f8961285-c05d-4414-b52b-4cf88f651405.png)

**Comment by kuangshp** [comment]
你可以加我，我远程看看，我们使用都没问题的
